version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm install express-generator
      - npm install ejs
      - npm install mysql
      - npm install express