version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - backend
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf/initdb.d/:/docker-entrypoint-initdb.d/
    env_file:
      - .env


  web:
    image: node:latest
    environment:
      - MYSQL_SERVER=mysql
      - MYSQL_USER=myApp
      - MYSQL_PASSWORD=5656myApp2023
      - MYSQL_DATABASE=db
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend
    tty: true
    ports:
     - "8080:3000"
    volumes:
     - ./web:/app
    working_dir: /app
    command: >
        bash -c "npm install &&
        npm install nodemon -g &&
        npm install express-generator &&
        npm install ejs &&
        npm install mysql &&
        nodemon app.js"
    depends_on:
     - mysql

networks:
  backend:

volumes:
  mysqldata: