DROP DATABASE IF EXISTS myapp;
CREATE DATABASE myapp;

USE myapp;
SET CHARACTER SET utf8;

DROP TABLE IF EXISTS items;
CREATE TABLE items (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO items
VALUES(1, 'タロイモ');